/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/checkbox`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/icons/Check`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/select`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/icons/ChevronDown`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/icons/ChevronUp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/declare-item/[option]` | `/declare-item/[option]`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/declare-item` | `/declare-item`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/checkbox`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/icons/Check`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/select`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/icons/ChevronDown`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/icons/ChevronUp`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/declare-item/[option]` | `/declare-item/[option]`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/declare-item` | `/declare-item`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/../components/ui/checkbox${`?${string}` | `#${string}` | ''}` | `/../lib/icons/Check${`?${string}` | `#${string}` | ''}` | `/../components/ui/select${`?${string}` | `#${string}` | ''}` | `/../lib/icons/ChevronDown${`?${string}` | `#${string}` | ''}` | `/../lib/icons/ChevronUp${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/declare-item/[option]${`?${string}` | `#${string}` | ''}` | `/declare-item/[option]${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/declare-item${`?${string}` | `#${string}` | ''}` | `/declare-item${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/checkbox`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/icons/Check`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/select`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/icons/ChevronDown`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/icons/ChevronUp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/declare-item/[option]` | `/declare-item/[option]`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/declare-item` | `/declare-item`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/home` | `/home`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
