/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/items`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/declare-item/[option]`, params: Router.UnknownInputParams & { option: string | number; } } | { pathname: `/edit-item/[itemId]`, params: Router.UnknownInputParams & { itemId: string | number; } } | { pathname: `/item-delivred/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/item-details/[itemId]`, params: Router.UnknownInputParams & { itemId: string | number; } } | { pathname: `/profile/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/edit-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/items`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/declare-item/[option]`, params: Router.UnknownOutputParams & { option: string; } } | { pathname: `/edit-item/[itemId]`, params: Router.UnknownOutputParams & { itemId: string; } } | { pathname: `/item-delivred/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/item-details/[itemId]`, params: Router.UnknownOutputParams & { itemId: string; } } | { pathname: `/profile/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/edit-profile${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/items${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/items`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/+not-found` | `/declare-item/${Router.SingleRoutePart<T>}` | `/edit-item/${Router.SingleRoutePart<T>}` | `/item-delivred/${Router.SingleRoutePart<T>}` | `/item-details/${Router.SingleRoutePart<T>}` | `/profile/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/declare-item/[option]`, params: Router.UnknownInputParams & { option: string | number; } } | { pathname: `/edit-item/[itemId]`, params: Router.UnknownInputParams & { itemId: string | number; } } | { pathname: `/item-delivred/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/item-details/[itemId]`, params: Router.UnknownInputParams & { itemId: string | number; } } | { pathname: `/profile/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
